name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy assets into template (if present)
        run: |
          if [ -d "assets" ]; then
            mkdir -p template/assets
            cp -r assets/* template/assets/ || true
          fi
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./template
          publish_branch: gh-pages
          user_name: GitHub Actions
          user_email: actions@github.com
